### ISSUE TITLE
Publish new version on Rubygems

### ISSUE THREAD

**Issue by kuahyeow** [ezza/pleasant-lawyer#3]
Can a new version please be published for https://rubygems.org/gems/pleasant-lawyer ?

**Comment by mogest** [comment]
Hey @ezza, if you give me rubygems push rights I can keep this going.

**Comment by ezza** [comment]
I've added your github email as an owner @mogest but it doesn't seem to have picked it up, do you have an account on rubygems with the same address?

@kuahyeow there's a version 0.5.0 there now.

**Comment by kuahyeow** [comment]
Awesome, thanks !
